"📌 area: cli":
  - any: ["cli/src/*", "cli/src/**/*"]

"📌 area: t3-app":
  - any: ["cli/template/*", "cli/template/**/*"]

"📚 documentation":
  - any: ["www/*", "www/**/*", "**/*.md"]

"📌 area: ci":
  - any: [".github/workflows/*", ".github/workflows/**/*"]
